
# resume information
resume-index = 28939
seed = 12849284977934393636
rate = 100       
shard = 1/1
nocapture = servername


adapter-ip = 172.168.72.99
# TARGET SELECTION (IP, PORTS, EXCLUDES)
ports = 0-1024
range = 172.168.72.0/24

